package ru.pokrovskii.design.theme

import androidx.compose.ui.graphics.Color

internal val md_theme_light_primary = Color(0xFF006A68)
internal val md_theme_light_onPrimary = Color(0xFFFFFFFF)
internal val md_theme_light_primaryContainer = Color(0xFF6FF7F3)
internal val md_theme_light_onPrimaryContainer = Color(0xFF00201F)
internal val md_theme_light_secondary = Color(0xFF4A6362)
internal val md_theme_light_onSecondary = Color(0xFFFFFFFF)
internal val md_theme_light_secondaryContainer = Color(0xFFCCE8E6)
internal val md_theme_light_onSecondaryContainer = Color(0xFF051F1F)
internal val md_theme_light_tertiary = Color(0xFF4A607B)
internal val md_theme_light_onTertiary = Color(0xFFFFFFFF)
internal val md_theme_light_tertiaryContainer = Color(0xFFD2E4FF)
internal val md_theme_light_onTertiaryContainer = Color(0xFF021D35)
internal val md_theme_light_error = Color(0xFFBA1A1A)
internal val md_theme_light_errorContainer = Color(0xFFFFDAD6)
internal val md_theme_light_onError = Color(0xFFFFFFFF)
internal val md_theme_light_onErrorContainer = Color(0xFF410002)
internal val md_theme_light_background = Color(0xFFFAFDFC)
internal val md_theme_light_onBackground = Color(0xFF191C1C)
internal val md_theme_light_surface = Color(0xFFFAFDFC)
internal val md_theme_light_onSurface = Color(0xFF191C1C)
internal val md_theme_light_surfaceVariant = Color(0xFFDAE5E3)
internal val md_theme_light_onSurfaceVariant = Color(0xFF3F4948)
internal val md_theme_light_outline = Color(0xFF6F7978)
internal val md_theme_light_inverseOnSurface = Color(0xFFEFF1F0)
internal val md_theme_light_inverseSurface = Color(0xFF2D3131)
internal val md_theme_light_inversePrimary = Color(0xFF4DDAD6)
internal val md_theme_light_shadow = Color(0xFF000000)
internal val md_theme_light_surfaceTint = Color(0xFF006A68)
internal val md_theme_light_outlineVariant = Color(0xFFBEC9C7)
internal val md_theme_light_scrim = Color(0xFF000000)

internal val md_theme_dark_primary = Color(0xFF4DDAD6)
internal val md_theme_dark_onPrimary = Color(0xFF003736)
internal val md_theme_dark_primaryContainer = Color(0xFF00504E)
internal val md_theme_dark_onPrimaryContainer = Color(0xFF6FF7F3)
internal val md_theme_dark_secondary = Color(0xFFB0CCCA)
internal val md_theme_dark_onSecondary = Color(0xFF1B3534)
internal val md_theme_dark_secondaryContainer = Color(0xFF324B4A)
internal val md_theme_dark_onSecondaryContainer = Color(0xFFCCE8E6)
internal val md_theme_dark_tertiary = Color(0xFFB2C8E8)
internal val md_theme_dark_onTertiary = Color(0xFF1B324B)
internal val md_theme_dark_tertiaryContainer = Color(0xFF324863)
internal val md_theme_dark_onTertiaryContainer = Color(0xFFD2E4FF)
internal val md_theme_dark_error = Color(0xFFFFB4AB)
internal val md_theme_dark_errorContainer = Color(0xFF93000A)
internal val md_theme_dark_onError = Color(0xFF690005)
internal val md_theme_dark_onErrorContainer = Color(0xFFFFDAD6)
internal val md_theme_dark_background = Color(0xFF191C1C)
internal val md_theme_dark_onBackground = Color(0xFFE0E3E2)
internal val md_theme_dark_surface = Color(0xFF191C1C)
internal val md_theme_dark_onSurface = Color(0xFFE0E3E2)
internal val md_theme_dark_surfaceVariant = Color(0xFF3F4948)
internal val md_theme_dark_onSurfaceVariant = Color(0xFFBEC9C7)
internal val md_theme_dark_outline = Color(0xFF889392)
internal val md_theme_dark_inverseOnSurface = Color(0xFF191C1C)
internal val md_theme_dark_inverseSurface = Color(0xFFE0E3E2)
internal val md_theme_dark_inversePrimary = Color(0xFF006A68)
internal val md_theme_dark_shadow = Color(0xFF000000)
internal val md_theme_dark_surfaceTint = Color(0xFF4DDAD6)
internal val md_theme_dark_outlineVariant = Color(0xFF3F4948)
internal val md_theme_dark_scrim = Color(0xFF000000)


internal val seed = Color(0xFF006A68)